version: 0.2

phases:
  pre_build:
    commands:
      - echo "[CODEBUILD] pre_build started at $(date)"
      - echo Logging in to docker hub...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo "[CODEBUILD] build started at $(date)"
      - echo Building the Docker image...
      - docker build -t $IMG_REPOSITORY:$IMG_TAG .
      - echo "[CODEBUILD] build finished at $(date)"
  post_build:
    commands:
      - echo "[CODEBUILD] post_build started at $(date)"
      - echo Pushing the Docker images...
      - docker push $IMG_REPOSITORY:$IMG_TAG
      - echo "[CODEBUILD] post_build completed at $(date)"
